# Generated by Django 4.1.2 on 2022-11-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTodoInformatica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
